typography_spectrum: 0.8649164063390344
color:
  brandColors:
    - '#060203'
    - '#77a2d5'
    - '#b1d3f9'
    - '#4477b0'
    - '#fefefe'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Finding Light
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: thgiL gnidniF
purpose: []
