name: Finding Light
favicon: null
layout_spectrum: 0.7991635466460139
typography_spectrum: 0.8649164063390344
title: Photography with Purpose
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f7f7f7'
    - '#53352b'
    - '#626d83'
    - '#feaa62'
  brandStrength: 0
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
